workspace:
  base: /var/www/owncloud
  path: apps/openidconnect

branches: [ master, release* ]

pipeline:
  install-server:
    image: owncloudci/core
    pull: true
    version: daily-stable10-qa
    db_type: ${DB_TYPE}
    db_name: ${DB_NAME=owncloud}
    db_host: ${DB_TYPE}
    db_username: autotest
    db_password: owncloud
    when:
      matrix:
        NEED_SERVER: true

  install-app:
    image: owncloudci/php
    pull: true
    environment:
      - COMPOSER_HOME=/var/www/owncloud/apps/openidconnect/.cache/composer
    commands:
      - make vendor
      - cd /var/www/owncloud/
      - php occ a:l
      - php occ a:e openidconnect
      - php occ a:e testing
      - php occ a:l
    when:
      matrix:
        NEED_INSTALL_APP: true

  owncloud-coding-standard:
    image: owncloudci/php
    pull: true
    environment:
      - COMPOSER_HOME=/var/www/owncloud/apps/openidconnect/.cache/composer
    commands:
      - make test-php-style
    when:
      matrix:
        TEST_SUITE: owncloud-coding-standard

  phpstan:
    # phpstan requires php7.1
    image: owncloudci/php:7.1
    pull: true
    environment:
      - COMPOSER_HOME=/var/www/owncloud/apps/openidconnect/.cache/composer
    commands:
      - make test-php-phpstan
    when:
      matrix:
        TEST_SUITE: php-stan

  phan-70:
    # phan requires a recent php-ast extension
    image: owncloudci/php:7.0
    pull: true
    environment:
      - COMPOSER_HOME=/var/www/owncloud/apps/openidconnect/.cache/composer
    commands:
      - make test-php-phan
    when:
      matrix:
        TEST_SUITE: phan

  phan-71:
    # phan requires a recent php-ast extension
    image: owncloudci/php:7.1
    pull: true
    environment:
      - COMPOSER_HOME=/var/www/owncloud/apps/openidconnect/.cache/composer
    commands:
      - make test-php-phan
    when:
      matrix:
        TEST_SUITE: phan

  phan-72:
    # phan requires a recent php-ast extension
    image: owncloudci/php:7.2
    pull: true
    environment:
      - COMPOSER_HOME=/var/www/owncloud/apps/openidconnect/.cache/composer
    commands:
      - make test-php-phan
    when:
      matrix:
        TEST_SUITE: phan

  php-unit:
    image: owncloudci/php
    pull: true
    commands:
      - make test-php-unit-dbg
    when:
      matrix:
        TEST_SUITE: php-unit

  php-integration:
    image: owncloudci/php
    pull: true
    commands:
      - make test-php-integration-dbg
    when:
      matrix:
        TEST_SUITE: php-integration

  test-javascript:
    image: owncloudci/php
    pull: true
    commands:
      - make test-js
    when:
      matrix:
        TEST_SUITE: javascript

  codecov:
    image: plugins/codecov:2
    secrets: [codecov_token]
    pull: true
    files:
      - tests/output/clover-unit.xml
    when:
      matrix:
        COVERAGE: true

  build:
    image: owncloudci/php
    pull: true
    commands:
      - make -f Makefile.release dist
    when:
     matrix:
       TEST_SUITE: build

services:
  mysql:
    image: mysql:5.5
    environment:
    - MYSQL_USER=autotest
    - MYSQL_PASSWORD=owncloud
    - MYSQL_DATABASE=${DB_NAME=owncloud}
    - MYSQL_ROOT_PASSWORD=owncloud
    when:
      matrix:
        DB_TYPE: mysql

  pgsql:
    image: postgres:9.4
    environment:
    - POSTGRES_USER=autotest
    - POSTGRES_PASSWORD=owncloud
    - POSTGRES_DB=${DB_NAME=owncloud}
    when:
      matrix:
        DB_TYPE: pgsql

  oci:
    image: deepdiver/docker-oracle-xe-11g
    environment:
    - ORACLE_USER=system
    - ORACLE_PASSWORD=oracle
    - ORACLE_DB=${DB_NAME=owncloud}
    when:
      matrix:
        DB_TYPE: oci

matrix:
  include:
  # owncloud-coding-standard
  - PHP_VERSION: 7.2
    TEST_SUITE: owncloud-coding-standard

  # php-stan
  - PHP_VERSION: 7.2
    TEST_SUITE: php-stan
    NEED_SERVER: true
    NEED_INSTALL_APP: true

  # phan
  - PHP_VERSION: 7.2
    TEST_SUITE: phan
    NEED_SERVER: true

  # build
  - PHP_VERSION: 7.2
    TEST_SUITE: build

  # Test suites
  # php70
  - PHP_VERSION: 7.0
    OC_VERSION: daily-stable10-qa
    TEST_SUITE: php-unit
    DB_TYPE: mysql
    NEED_SERVER: true
    NEED_INSTALL_APP: true
    COVERAGE: true

  - PHP_VERSION: 7.0
    OC_VERSION: daily-stable10-qa
    TEST_SUITE: php-integration
    DB_TYPE: mysql
    NEED_SERVER: true
    NEED_INSTALL_APP: true
    COVERAGE: true

  - PHP_VERSION: 7.0
    OC_VERSION: daily-stable10-qa
    TEST_SUITE: php-unit
    DB_TYPE: pgsql
    NEED_SERVER: true
    NEED_INSTALL_APP: true
    COVERAGE: true

  - PHP_VERSION: 7.0
    OC_VERSION: daily-stable10-qa
    TEST_SUITE: php-integration
    DB_TYPE: pgsql
    NEED_SERVER: true
    NEED_INSTALL_APP: true
    COVERAGE: true

  # php71
  - PHP_VERSION: 7.1
    OC_VERSION: daily-stable10-qa
    TEST_SUITE: php-unit
    DB_TYPE: mysql
    NEED_SERVER: true
    NEED_INSTALL_APP: true
    COVERAGE: true

  - PHP_VERSION: 7.1
    OC_VERSION: daily-stable10-qa
    TEST_SUITE: php-integration
    DB_TYPE: mysql
    NEED_SERVER: true
    NEED_INSTALL_APP: true
    COVERAGE: true

  - PHP_VERSION: 7.1
    OC_VERSION: daily-stable10-qa
    TEST_SUITE: php-unit
    DB_TYPE: pgsql
    NEED_SERVER: true
    NEED_INSTALL_APP: true
    COVERAGE: true

  - PHP_VERSION: 7.1
    OC_VERSION: daily-stable10-qa
    TEST_SUITE: php-integration
    DB_TYPE: pgsql
    NEED_SERVER: true
    NEED_INSTALL_APP: true
    COVERAGE: true

  # php72
  - PHP_VERSION: 7.2
    OC_VERSION: daily-stable10-qa
    TEST_SUITE: php-unit
    DB_TYPE: mysql
    NEED_SERVER: true
    NEED_INSTALL_APP: true
    COVERAGE: true

  - PHP_VERSION: 7.2
    OC_VERSION: daily-stable10-qa
    TEST_SUITE: php-integration
    DB_TYPE: mysql
    NEED_SERVER: true
    NEED_INSTALL_APP: true
    COVERAGE: true

  - PHP_VERSION: 7.2
    OC_VERSION: daily-stable10-qa
    TEST_SUITE: php-unit
    DB_TYPE: pgsql
    NEED_SERVER: true
    NEED_INSTALL_APP: true
    COVERAGE: true

  - PHP_VERSION: 7.2
    OC_VERSION: daily-stable10-qa
    TEST_SUITE: php-integration
    DB_TYPE: pgsql
    NEED_SERVER: true
    NEED_INSTALL_APP: true
    COVERAGE: true
