name: PHP Composer Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: owncloudci/php:7.3
    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Update lockfile
        run: composer update --ignore-platform-reqs
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
#      - name: Run PHP Unit tests
#        run: make test-php-unit
      - name: Building dist
        run: make dist
      - name: Built app distribution
        run: ls -R build
      - name: Release app distribution assets
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v1
        with:
          files: build/dist/cesnet-openidconnect.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
